language: python

python:
  - 2.6
  - 2.7
  - pypy

before_install: pip install --use-mirrors -r requirements.txt

install: python setup.py install

script: nosetests -v --with-coverage --cover-erase --cover-package wsgiproxy

